Add classes
wacoo/school-library-system pull request #1
Opened 2023-10-09 11:37 UTC by wacoo

- Add person class, its attributes and methods
- Add student class, its attributes and methods
- Add teacher class, its attributes and methods

2023-10-09 14:21 UTC, iambenkis requested changes
#### Hi @wacoo  

Good job so far!
There are some issues that you still need to work on to prepare your project for the final evaluation but you are almost there!
You did a great job, keep up the good work 👍🏼

![giphy](https://user-images.githubusercontent.com/25227022/169391888-8dd8108f-0d42-4e54-87cc-a3f9fd392dbc.gif)


## Highlights

✔️ Person class added
✔️ Student class added
✔️ Teacher class added

## Suggested changes
_Check the comments under the review._

You can use as many of my suggestions as you want. If there is anything you would like to skip - feel free to do that. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2023-10-09 14:21 UTC, iambenkis commented on person.rb
> +    @name = name
- [ ] Good job setting default value for optional variable 👍 , As for the `age` variable , it should not be defined with a default value as it is not a optional variable . Note that default value should defined as  "Unknown" for name and true for parent_permission  , Kindly fix that 👍 

![Capture](https://github.com/wacoo/school-library-system/assets/80458199/3570d395-053b-40fc-9190-b020a5a14ea1)

```ruby
class Person
.
.
.
def initialize(age, name = "Unknown", parent_permission = true)
    @id = Random.rand(1..1000)
    @age = age
    @name = name
    @parent_permission = parent_permission
  end
.
.
.
end
```

2023-10-09 14:21 UTC, iambenkis commented on student.rb
> +
- [ ] Student class is well created , however , it should have the optional (or default) value for `name` and for `parent_permission` parameters as describe to in the parent class, Kindly add them 👍 

```ruby
class  Student < Person
 .
 .
 .
  def initialize(age, classroom, name = "Unknown", parent_permission = true)
       #...
  end
 .
 .
 .
end
```

2023-10-09 14:21 UTC, iambenkis commented on teacher.rb
> +    @specialization = specialization
- [ ] Same thing for the Teacher class  which is well created , but  the optional (or default) value for `name` and for `parent_permission` parameters are not defined, Kindly add them 👍 

```ruby
class Teacher < Person
 .
 .
 .
  def initialize(age, specialization, name = "Unknown", parent_permission = true)
       #...
  end
 .
 .
 .
end
```

2023-10-10 05:46 UTC, FrederickMih requested changes
## Hi :raising_hand: :raising_hand: @wacoo , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


:tada: :champagne: <img src="https://media.giphy.com/media/LtkRsMZNSChvICUFhV/giphy.gif"  width ="160"><img> :tada: :champagne: 

## Highlights :green_circle: 

- Default value for the optional name param was modified as requested :+1: 

## Optional suggestions
**N/A**

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-10-10 05:46 UTC, FrederickMih commented on person.rb
> +  def initialize(age, name = 'Unknown', parent_permission = nil)
- [ ] Hi @wacoo, please let's check the previous reviewer comment once more. He even use a screenshot from the requirements showing that the default value for the parent_permission parameter is `true` and not `nil`. Please let's adhere to the requirements.

2023-10-10 05:46 UTC, FrederickMih commented on student.rb
> +  def initialize(classroom, age, name = 'Unknown', parent_permission = nil)
- [ ] You did an excellent job by setting the default value for the name parameter to "Unkown" as requested. Unfortunately you forgot to change `nil` to `true`. Working once more on this, will ensure that you'll always abide and work based on the requirements provided by your client in future :smile:

2023-10-10 05:46 UTC, FrederickMih commented on teacher.rb
> +  def initialize(specialization, age, name = 'Unknown', parent_permission = nil)
- [ ] Please check once more the optional value for the parent_permission parameter. It takes a boolean value(`true`) as the default value :+1:

2023-10-10 08:26 UTC, TedLivist approved these changes
## STATUS: APPROVED ✔️ ✔️

Hi @wacoo,

✔️ Implementation of classes in different files based on convention

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-10-10 12:59 UTC, merged